import type { ApiAssociationActiveAssociationActive } from '@strapi-types/contentTypes';
import type { ApiAssociationPageAssociationPage } from '@strapi-types/contentTypes';
import type { ApiBecomeAMemberPageBecomeAMemberPage } from '@strapi-types/contentTypes';
import type { ApiCoachCoach } from '@strapi-types/contentTypes';
import type { ApiContactInformationContactInformation } from '@strapi-types/contentTypes';
import type { ApiFrequentlyAskedQuestionsPageFrequentlyAskedQuestionsPage } from '@strapi-types/contentTypes';
import type { ApiHomePageHomePage } from '@strapi-types/contentTypes';
import type { ApiMartialArtInformationMartialArtInformation } from '@strapi-types/contentTypes';
import type { ApiMemberCommentMemberComment } from '@strapi-types/contentTypes';
import type { ApiTrainingsPageTrainingsPage } from '@strapi-types/contentTypes';

export type AssociationActive = ApiAssociationActiveAssociationActive['attributes'];
export type AssociationPage = ApiAssociationPageAssociationPage['attributes'];
export type BecomeAMemberPage = ApiBecomeAMemberPageBecomeAMemberPage['attributes'];
export type Coach = ApiCoachCoach['attributes'];
export type ContactInformation = ApiContactInformationContactInformation['attributes'];
export type FrequentlyAskedQuestionsPage = ApiFrequentlyAskedQuestionsPageFrequentlyAskedQuestionsPage['attributes'];
export type HomePage = ApiHomePageHomePage['attributes'];
export type MartialArtInformation = ApiMartialArtInformationMartialArtInformation['attributes'];
export type MemberComment = ApiMemberCommentMemberComment['attributes'];
export type TrainingsPage = ApiTrainingsPageTrainingsPage['attributes'];
